import pickle

def classify_email(email):
    with open('models/spam_classifier.pkl', 'rb') as f:
        model, vectorizer = pickle.load(f)
    
    email_vectorized = vectorizer.transform([email])
    
    prediction = model.predict(email_vectorized)[0]
    return "Spam" if prediction == 1 else "Ham"

if __name__ == "__main__":
    email = input("Enter an email to classify: ")
    result = classify_email(email)
    print(f"The email is: {result}")

'''
Purpose: Classifies new email content as "Spam" or "Ham".
'''

'''
Role: Loads the trained model and vectorizer from spam_classifier.pkl.
Takes user input (email text), vectorizes it using the saved vectorizer, and predicts its label using the saved model.
Outputs whether the email is spam or ham.
'''

'''
Dependencies: Relies on spam_classifier.pkl generated by train.py.
'''